[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed=115200

lib_deps =
    https://github.com/informatik-aalen/AALeC-V3
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21
    adafruit/Adafruit NeoPixel@^1.11.0
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.4.0
    madhephaestus/WiiChuck@^0.4.1
    adafruit/Adafruit BME280 Library@^2.2.2
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit BME680 Library@^2.0.1
    adafruit/Adafruit Unified Sensor@^1.1.9